### ISSUE TITLE
Invalidate should try catch to guard against errors in destroy

### ISSUE THREAD

**Issue by gerritjvv** [gerritjvv/kafka-fast#20]
```
ava.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at kafka_clj.tcp$close_BANG_.invokeStatic(tcp.clj:104)
        at kafka_clj.tcp$close_BANG_.invoke(tcp.clj:100)
        at kafka_clj.tcp$tcp_pool$fn__17163.invoke(tcp.clj:119)
        at kafka_clj.pool$keyed_obj_factory$reify__17073.destroyObject(pool.clj:76)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.destroy(GenericKeyedObjectPool.java:1047)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.invalidateObject(GenericKeyedObjectPool.java:575)
        at kafka_clj.pool$fn__17059.invokeStatic(pool.clj:25)
        at kafka_clj.pool$fn__17059.invoke(pool.clj:20)
        at kafka_clj.pool$fn__17040$G__17005__17049.invoke(pool.clj:13)
        at kafka_clj.tcp$invalidate_BANG_.invokeStatic(tcp.clj:130)
        at kafka_clj.tcp$invalidate_BANG_.invoke(tcp.clj:129)
        at kafka_clj.consumer.consumer$process_wu_BANG_.invokeStatic(consumer.clj:185)
        at kafka_clj.consumer.consumer$process_wu_BANG_.invoke(consumer.clj:152)
        at kafka_clj.consumer.consumer$auto_tune_fetch.invokeStatic(consumer.clj:238)
        at kafka_clj.consumer.consumer$auto_tune_fetch.invoke(consumer.clj:233)
        at clojure.lang.AFn.applyToHelper(AFn.java:171)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:652)
        at clojure.core$partial$fn__4765.doInvoke(core.clj:2534)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at kafka_clj.consumer.consumer$start_wu_publisher_BANG_$fn__19398$fn__19399$fn__19400.invoke(consumer.clj:117)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gerritjvv** [comment]
fixed
