### ISSUE TITLE
Cannot cast to Map error in new pool design on close

### ISSUE THREAD

**Issue by gerritjvv** [gerritjvv/kafka-fast#38]
```
java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to clojure.lang.ITransientMap
        at clojure.core$dissoc_BANG_.invokeStatic(core.clj:3272)
        at clojure.core$dissoc_BANG_.invoke(core.clj:3272)
        at kafka_clj.pool.keyed$remove_keyed_pool$fn__1875.invoke(keyed.clj:34)
        at clojure.lang.Atom.swap(Atom.java:37)
        at clojure.core$swap_BANG_.invokeStatic(core.clj:2260)
        at clojure.core$swap_BANG_.invoke(core.clj:2253)
        at kafka_clj.pool.keyed$remove_keyed_pool.invokeStatic(keyed.clj:30)
        at kafka_clj.pool.keyed$remove_keyed_pool.invoke(keyed.clj:29)
        at kafka_clj.pool.keyed.AtomKeyedObjPool._keyed_pool_close(keyed.clj:116)
        at kafka_clj.pool.api$close_all.invokeStatic(api.clj:88)
        at kafka_clj.pool.api$close_all.invoke(api.clj:84)
        at kafka_clj.tcp$invalidate_BANG_.invokeStatic(tcp.clj:151)
        at kafka_clj.tcp$invalidate_BANG_.invoke(tcp.clj:148)
        at kafka_clj.consumer.consumer$process_wu_BANG_.invokeStatic(consumer.clj:200)
```

**Comment by gerritjvv** [comment]
this is due to using a transient dissoc.
